name: Build three-resume Next.js
on: push
jobs: 
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies and build output
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install npm dependencies
        run: npm ci

      - name: List files in components directory
        run: ls -la app/components/

      - name: Build assets
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /three-resume